import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { radioGrostek } from "@/assets/fonts";
import { Navbar } from "@/components/layout/navbar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${(geistSans.className, radioGrostek.variable)} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
