// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Navigation": {
    "home": "Home",
    "company": "Company",
    "aboutUs": "About Us",
    "leadershipTeam": "Leadership Team",
    "insights": "Insights & News",
    "airFreight": "Air Freight",
    "seaFreight": "Sea Freight",
    "landFreight": "Land Freight",
    "projectCargo": "Project Cargo",
    "packing": "Packing",
    "warehousing": "Warehousing",
    "exhibitionCargo": "Exhibition Cargo",
    "MovingLashing": "Moving & Lashing",
    "services": "Services",
    "trackShipment": "Track Shipment",
    "contact": "Contact",
    "getQuote": "Get a Quote"
  },
  "HomePage": {
    "hero": {
      "title": {
        "firstLine": "Your Trusted Partner in",
        "secondLine": "Logistics and Freight Delivery"
      },
      "inputPlaceholder": "Track your shipment"
    },
    "about": {
      "title": "Reliable Logistics Partner Across the Globe",
      "description": "At Maxline Global, we connect businesses to markets across the world. With our comprehensive logistics partner and commitment to service excellence, we ensure your cargo moves with speed, safety, and precision.",
      "type": {
        "air": "Air / 01",
        "sea": "Sea / 02",
        "road": "Road / 03"
      }
    },
    "services": {
      "heading": {
        "first": "Built to Empower",
        "second": "Efficiency"
      },
      "description": "Maxline turns fragmented workflows into unified strategies. Whether you're in the office or across the globe, we're one connected force",
      "btnText": "Explore our services",
      "title": "Integrated freight solutions tailored to your exact specifications.",
      "service": {
        "landFreight": {
          "title": "Land Freight",
          "description": "Efficient and Secure Road Transportation Across the GCC."
        },
        "airFreight": {
          "title": "Air Freight",
          "description": "Swift Air Freight Solutions for Global Reach."
        },
        "seaFreight": {
          "title": "Sea Freight",
          "description": "Reliable Sea Freight Services Across Continents."
        },
        "projectCargo": {
          "title": "Project Cargo",
          "description": "Specialized Handling for Heavy and Oversized Cargo."
        },
        "warehousing": {
          "title": "Warehousing",
          "description": "Strategic Warehousing and Distribution Solutions."
        },
        "movingLashing": {
          "title": "Moving & Lashing",
          "description": "Professional Relocation and Cargo Securing for Safe Transit.."
        }
      },
      "cta": {
        "title": "Logistics Without Limits",
        "description": "Our tailored freight solutions are engineered to meet the demands of  modern trade - ensuring every shipment arrives on time, on budget, and without compromise.",
        "btnText": "Explore more"
      }
    },
    "faq": {
      "title": "Frequently Asked Questions",
      "description": "Discover quick answers to the questions our clients ask most. From shipment tracking to specialized cargo handling, our FAQ section covers everything you need to know about Maxline Global's services, capabilities, and commitment to smooth, secure, and on-time delivery."
    },
    "faqList": [
      {
        "question": "What logistics services does Maxline Global offer?",
        "answer": "Maxline Global provides a full range of logistics solutions including sea, air, and land freight, customs clearance, warehousing, project cargo handling, chartering, and more — tailored to your business needs across the GCC and beyond."
      },
      {
        "question": "Which regions or countries does Maxline Global serve?",
        "answer": "We operate globally with a strong presence across the GCC countries, Asia, Europe, Africa, and the Americas. Our network enables seamless international trade and efficient cargo movement across all major trade lanes."
      },
      {
        "question": "Do you handle dangerous or hazardous cargo?",
        "answer": "Yes. Maxline Global is certified and experienced in handling hazardous and non-hazardous materials, including chemicals and reefer (temperature-controlled) cargo. Our team follows strict safety standards and international regulations."
      },
      {
        "question": "Can you manage oversized or project cargo?",
        "answer": "Absolutely. We offer project logistics solutions including heavy lift transport, Ro/Ro services, aircraft/ship chartering, and military or government shipment handling. We also provide port supervision and route planning for complex cargo."
      },
      {
        "question": "Do you provide warehousing and distribution services?",
        "answer": "Yes. We operate modern warehousing facilities in and around Jebel Ali Free Zone (JAFZA) with services like palletizing, shrink wrapping, labeling, and web-based inventory management. We also offer local and international distribution services."
      },
      {
        "question": "How can I track my shipment?",
        "answer": "We provide an easy-to-use Track & Trace system for real-time shipment updates. Clients can log in to our portal to view current location, estimated delivery time, and shipment history."
      },
      {
        "question": "Do you provide door-to-door logistics services?",
        "answer": "Yes. We offer door-to-door, door-to-port, and port-to-door services for both LCL (Less than Container Load) and FCL (Full Container Load) shipments. This includes document handling, customs clearance, and final delivery."
      },
      {
        "question": "How do I get a quote for freight services?",
        "answer": "Our team is available Monday to Friday, from 9:00 AM to 6:00 PM (UAE time). We are closed on weekends and public holidays. For urgent shipments, we can make special arrangements."
      },
      {
        "question": "What are your business hours?",
        "answer": "Our team is available Monday to Friday, from 9:00 AM to 6:00 PM (UAE time). We are closed on weekends and public holidays. For urgent shipments, we can make special arrangements."
      },
      {
        "question": "Why should I choose Maxline Global as my logistics partner?",
        "answer": "Maxline Global combines deep industry experience, a global network, and advanced logistics technology to offer flexible, scalable, and cost-effective supply chain solutions. We prioritize customer satisfaction, accuracy, and on-time delivery for every shipment."
      },
      {
        "question": "What types of cargo does Maxline Global handle?",
        "answer": "Maxline Global handles a wide range of cargo, including general freight, hazardous and non-hazardous goods, temperature-sensitive shipments, oversized project cargo, and time-critical deliveries by land, sea, and air."
      },
      {
        "question": "Do you provide customs clearance services?",
        "answer": "Yes, we offer comprehensive customs brokerage services for import, export, and transshipment across sea and air freight. Our team ensures compliance and smooth clearance through all major ports."
      }
    ],
    "insights": {
      "title": "<span>Maxline</span> Insights & Updates",
      "description": "Stay ahead with the latest in logistics, trade, and global supply chain trends.",
      "btnText": "More",
      "readBtn": "Read Article",
      "exploreBtn": "Explore More"
    },
    "insightsList": [
      {
        "id": 1,
        "title": "What is cross-trade shipping and when is it the best option?",
        "description": "A quick look at how cross-trade shipping works, when to use it, and how Maxline Global makes it seamless.",
        "image": "/images/blogs/scene-with-photorealistic-logistics-operations-proceedings.jpg",
        "slug": "cross-trade-shipping-guide"
      },
      {
        "id": 2,
        "title": "What is cross-trade shipping and when is it the best option?",
        "description": "A quick look at how cross-trade shipping works, when to use it, and how Maxline Global makes it seamless.",
        "image": "/images/blogs/transport-logistics-products (2).jpg",
        "slug": "cross-trade-shipping-guide"
      },
      {
        "id": 3,
        "title": "What is cross-trade shipping and when is it the best option?",
        "description": "A quick look at how cross-trade shipping works, when to use it, and how Maxline Global makes it seamless.",
        "image": "/images/blogs/transport-logistics-products.jpg",
        "slug": "cross-trade-shipping-guide"
      },
      {
        "id": 4,
        "title": "What is cross-trade shipping and when is it the best option?",
        "description": "A quick look at how cross-trade shipping works, when to use it, and how Maxline Global makes it seamless.",
        "image": "/images/blogs/truck-logistics-operation-dusk.jpg",
        "slug": "cross-trade-shipping-guide"
      },
      {
        "id": 5,
        "title": "What is cross-trade shipping and when is it the best option?",
        "description": "A quick look at how cross-trade shipping works, when to use it, and how Maxline Global makes it seamless.",
        "image": "/images/blogs/scene-with-photorealistic-logistics-operations-proceedings.jpg",
        "slug": "cross-trade-shipping-guide"
      },
      {
        "id": 6,
        "title": "What is cross-trade shipping and when is it the best option?",
        "description": "A quick look at how cross-trade shipping works, when to use it, and how Maxline Global makes it seamless.",
        "image": "/images/blogs/scene-with-photorealistic-logistics-operations-proceedings.jpg",
        "slug": "cross-trade-shipping-guide"
      }
    ]
  },
  "Cta": {
    "title": "Ready to move your business forward?",
    "description": "Partner with Maxline Global for reliable logistics solutions.",
    "call": "Call for enquiry",
    "email": "Send us email",
    "phone": "+97142822022",
    "emailAddress": "reception@maxlineglobal.com"
  },
  "Footer": {
    "slogan1": "Your trusted logistics partner, moving forward,",
    "slogan2": "every day.",
    "locationLabel": "Location:",
    "locationAddress": "Jebel Ali Free Zone, Dubai.",
    "getQuote": "Get A Quote",
    "general": "General",
    "about": "About",
    "home": "Home",
    "team": "Team",
    "insights": "Insights & Updates",
    "contact": "Contact",
    "services": "Services",
    "support": "Support",
    "trackShipment": "Track your Shipment",
    "getQuoteShort": "Get Quote",
    "technicalSupport": "Technical Support",
    "social": "Social",
    "linkedin": "Linkedin",
    "instagram": "Instagram",
    "facebook": "Facebook",
    "x": "X",
    "copyright": "© {year} Maxline Globals. All Rights Reserved.",
    "designedBy": "Designed & Developed by {agency}",
    "agencyName": "Ziron Media",
    "airFreight": "Air Freight",
    "seaFreight": "Sea Freight",
    "landFreight": "Land Freight",
    "projectCargo": "Project Cargo",
    "packing": "Packing",
    "warehousing": "Warehousing",
    "exhibitionCargo": "Exhibition Cargo",
    "MovingLashing": "Moving & Lashing"
  },
  "AboutPage": {
    "badge": "About us",
    "heroTitle": "Building Smarter Supply Chains for a Connected World.",
    "whatWeDo": {
      "title": "What we do?",
      "description": "At <span>Maxline global</span> logistics solutions, our mission is to provide exceptional logistics services to our clients, enabling them to streamline their supply chain and focus on their core business operations. We have been serving our clients with top-notch freight forwarding end-to-end service from its inception."
    },
    "principles": {
      "title": "Our Core Principles:",
      "list": [
        {
          "label": "Vision",
          "title": "Leading with Vision, Moving with Purpose.",
          "description": "Our vision is to be the foremost leader in the freight forwarding industry, renowned for our innovative, sustainable, and customer-centric logistics solutions that redefine industry standards."
        },
        {
          "label": "Mission",
          "title": "Driven by Purpose. Defined by Progress.",
          "description": "Our mission is to deliver unparalleled excellence in freight forwarding by providing innovative, sustainable, and customer-focused solutions. We strive to exceed expectations, create lasting value for our clients, and drive progress in the logistics sector."
        },
        {
          "label": "Fast Service",
          "title": "Logistics at the Speed of Business.",
          "description": "We are committed to providing fast and reliable logistics services, ensuring the timely and efficient delivery of your goods. Our focus is on meeting and exceeding your expectations, helping your business thrive in today's fast-paced market. Experience the speed and efficiency of our logistics solutions."
        },
        {
          "label": "100% Accuracy",
          "title": "Delivering Accuracy, Every Time.",
          "description": "We guarantee 100% accuracy in every shipment through meticulous planning, streamlined processes, and efficient communication. Leveraging advanced technologies like real-time tracking and automation, we ensure precision and reliability, giving you peace of mind with every delivery. Trust us for accurate and dependable logistics solutions."
        }
      ]
    },
    "clients": {
      "label": "Our clients",
      "title": "These Companies Trust Us to Deliver Their Vision"
    },
    "words": "In a world where delays and cost overruns are common, Maxline Global Logistics delivers with precision. We commit to timelines and budgets—and we deliver. This promise drives how we train our teams, apply smart logistics technology, and serve clients worldwide.",
    "certification": {
      "title": "Certified for Excellence in Global Logistics",
      "description": "Maxline Global's certifications demonstrate our commitment to safe, efficient, and compliant logistics across air, sea, and land. We meet international standards in freight forwarding, warehousing, customs, and hazardous cargo-ensuring trust and reliability throughout the supply chain."
    }
  },
  "ServicesPage": {
    "title": "Logistics Services | Maxline Global",
    "description": "Explore our full suite of global logistics services—from air, sea, and road freight to warehousing, customs clearance, and project cargo management. Maxline Global delivers reliable, scalable, and end-to-end solutions for every supply chain challenge.",
    "keywords": "logistics services, global logistics, air freight, sea freight, road freight, warehousing, customs clearance, project cargo, supply chain solutions",
    "subtitle": "Services",
    "mainTitle": "Logistics Solutions That Move Business Forward",
    "ourServices": "Our Services"
  },
  "TeamPage": {
    "heroSubtitle": "Our Team",
    "heroTitle": "Here's the team that works hard to Deliver your vision, faster",
    "heroDescription": "Get to know the expert team behind Maxline Global. Our logistics professionals deliver innovative, efficient, and reliable supply chain solutions across the globe.",
    "leadershipTitle": "Leadership That Moves the World",
    "specialistsTitle": "Specialists in Motion",
    "personName": "Person Name",
    "designation": "Designation",
    "linkedinProfile": "Linkedin Profile",
    "departmentName": "Logistics Department",
    "departmentDescription": "Expert team handling freight forwarding, customs clearance, and supply chain solutions"
  }
};
export default messages;